Repository chingu-voyages/v25-geckos-team-04, pull requests merged in 2020-11, with the labels that each got.

#15 #10 add temperature degree component
  package.json
  public/index.html
  src/components/Temperature/Temperature.module.css
  src/components/Temperature/index.tsx
  src/components/index.tsx
  src/index.tsx
  src/styles/main.css
  yarn.lock
Labels: component, feature

#18 #8 add css variables
  src/styles/variables.css
Labels: feature

#17 #11 add weather title component
  src/components/WeatherTitle/WeatherTitle.module.css
  src/components/WeatherTitle/index.tsx
  src/components/index.tsx
Labels: component, feature

#19 [#9] WeatherIcon component
  src/_typings/import-png.d.ts
  src/assets/Clear.png
  src/assets/Cloud-background.png
  src/assets/Hail.png
  src/assets/HeavyCloud.png
  src/assets/HeavyRain.png
  src/assets/LightCloud.png
  src/assets/LightRain.png
  src/assets/Shower.png
  src/assets/Sleet.png
  src/assets/Snow.png
  src/assets/Thunderstorm.png
  src/components/Temperature/Temperature.module.css
  src/components/WeatherIcon/WeatherIcons.tsx
  src/components/WeatherIcon/index.tsx
  src/components/index.tsx
  src/styles/main.css
  tsconfig.json
Labels: component, feature

#24 Updated README
  README.md
Labels: documentation

#22 #12 Add current place
  src/components/CurrentPlace/CurrentPlace.module.css
  src/components/CurrentPlace/index.tsx
  src/components/index.tsx
Labels: component

#44 #43 missing components
  src/components/IconButton/IconButton.module.css
  src/components/IconButton/index.tsx
  src/components/Temperature/Temperature.module.css
  src/components/Temperature/index.tsx
  src/components/index.tsx
Labels: bug

#45 29 Add date component
  package.json
  src/components/DateComponent/Date.module.css
  src/components/DateComponent/index.tsx
  src/components/index.tsx
  yarn.lock
Labels: component, feature

#41 #31 add wind direction component
  src/components/IconButton/IconButton.module.css
  src/components/WeatherTitle/WeatherTitle.module.css
  src/components/WindDirection/WindDirection.module.css
  src/components/WindDirection/index.tsx
  src/components/index.tsx
Labels: component, feature

#49 27 Add weather card
  src/components/Temperature/Temperature.module.css
  src/components/Temperature/index.tsx
  src/components/WeatherCard/WeatherCard.module.css
  src/components/WeatherCard/index.tsx
  src/components/index.tsx
Labels: component

#46 #34 add Highlight List component
  src/components/HighlightList/HighlightList.module.css
  src/components/HighlightList/index.tsx
  src/components/index.tsx
Labels: component, feature

#62 [#32] Add PercentageBar component
  src/components/PercentageBar/PercentageBar.module.css
  src/components/PercentageBar/index.tsx
  src/styles/variables.css
Labels: component, feature

#50 #38 add CityLink component
  src/components/CityLink/CityLink.module.css
  src/components/CityLink/index.tsx
Labels: component, feature

#66 Renamed CityHistoryList to CitySearchList
  src/components/CitySearchList/CitySearchList.module.css
  src/components/CitySearchList/index.tsx
  src/components/index.tsx
Labels: component
